apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.6.0
    helm:
      releaseName: kube-prometheus-stack
      values: |
        {{ .Files.Get "values/prometheus-stack.values.yaml" | nindent 8 }}
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
