apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hawakening
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hawakening
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads/manifests/hawakening
    repoURL: https://github.com/hawakening/k8s-manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
