apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.6.26
    helm:
      releaseName: mongodb
      values: |
        {{ .Files.Get "values/mongodb.values.yaml" | nindent 8 }}
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: hawakening
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
