apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  annotations:
    tailscale.com/tailnet-fqdn: preometheus-stack-prometheus-stack-kube-prom-prometheus.dragon-nase.ts.net
  name: prometheus # service name
spec:
  externalName: placeholder # any value - will be overwritten by operator
  type: ExternalName
  ports:
    - name: http-web
      port: 9090
      targetPort: 9090
