---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: xmpp-admin
  namespace: hawakening
spec:
  encryptedData:
    password: AgCYqf9TFImDf+8uFiaWRIpFYizjcfqmIwu3jgyCNv3gdzTQJPeNPFvVXnd1wcdVbN46C5ZOdhm4qCYytzs4d/xYZ+uVKuZlokPgBRWX+Y9vfDxcmUaRO6SZuEMhRcEeeyUVtJ50u+kIzrRlA21+9qhpGukhR4AMFkS6LRYjy+hYiSZvEq/XYq9FKY3HWEwZtdCZci2ohH9XMKXXl6dSIpFp9zpaXlibXQ+FbVLnsujvAxsEpF6f0sGYbesngZjT0uqI1/0p4kIGz74WU/4ghGFt0r+hOzUKnzANzfOACLBXYw+gXmTsgsda5oSdDDAxcZ2oaVFx7HenD7FBIhUFzcRGpnI+3+APlbdIuu255+cidyxh6HxFJusnW+36x+PFgwMYzgMlZwyCzkSntfQe5o7XGx06MuVw2NwDQWUVsZ54CHqJYadUnFJ7MWcFAr8J2fveopUEUyQCG9E3yaWm8d21hj+/3B5HOxpP+vAmL01KZ4g40qdHziSYMzlPgRbvTuhJqY2QydTgoWXjoWSXjUuJyY1V1xABShdkiZxs52YqZicujBrje1kTMTs8Aau9VUiCrM1oyMB4W4lPpqQv2IKp9mtCGc2JWwnUxguGfPAT0kXPmvaEiATMl39+0xsgBHXpE/iDL5M6Z80NvJBaWnmUQQvveeswhKFA6hbe6GvSW/l67679ri+QB52+JT8jG/i0MYV5vnGGkkRUlOgbCeIdUvcbTsfj8qKNb7+KG/iAPpTkveCIZwk+v9DbCFEUDLo=
  template:
    metadata:
      name: xmpp-admin
      namespace: hawakening
    type: Opaque