grafana:
  crds.upgradeJob.enabled: true
  grafana.ini:
    server:
      root_url: https://grafana.hwkn.dev
  ingress:
    enabled: false
  persistence:
    enabled: true
    type: sts
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection
  ## Configure additional grafana datasources (passed through tpl)
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  plugins:
    - grafana-mongodb-datasource
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway.monitoring.svc.cluster.local
      access: proxy
    # - name: MongoDB
    #   type: grafana-mongodb-datasource
    #   access: proxy
    #   url: mongodb://mongodb-service:27017
    #   jsonData:
    #     connection_string: mongodb://mongodb-service:27017
    #     database_name: hawakening
    #   secureJsonData:
    #     password: your_password
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 100Gi
