apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.74.1
    helm:
      releaseName: tailscale-operator
      values: |
        {{ .Files.Get "templates/tailscale-operator/_values.yaml" | nindent 8 }}
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
