apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: default
  source:
    chart: alloy
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.9.2
    helm:
      releaseName: alloy
      values: |
        {{ .Files.Get "values/alloy.values.yaml" | nindent 8 }}
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
