apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hawakening
data:
  REDIS_SENTINEL_HOST: redis.hawakening.svc.cluster.local
  REDIS_SENTINEL_PORT: "26379"
  REDIS_MASTER_NAME: "mymaster"
  METEOR_URI: "http://services.hawakening.com"
  SITE_URL: "https://hawakening.com"
  MAIL_HOST: "smtp.sendgrid.net"
  MAIL_PORT: "465"
  MAIL_USER: "apikey"
  LOG_LEVEL: "info"
  # MONGOOSE_DEBUG: "true"
  SLOW_REQUEST_DEBUG_THRESHOLD: "500"
  # DISABLE_REGISTRATION: "true"
