---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: hawakening
spec:
  encryptedData:
    .dockerconfigjson: AgAwUvP/anPYjBsiB/ZlJ5WiZBmnggBf4chEyf2pKu7+3nU69YMNuWvnUr6Mhfj+pIkL5LkPQrSHzYZzZTp1JMqYmfTZ3GgXti4yADly1v8HsLiSJfnvk1n3LcWiyYGvVrg2Jpm/ps8EMi3ONLVr9AP40qPqxfE+RRmZfxSalBNwmHhNdEdUeYL/O0RNX70CU8CqnGCWzZaJPQIypnC2XdXu89r6rYL/+rg1tGWATAKUdbS/b8+8NEdUdYuttCL1V3S+vmd8fIbNcr4Y2eHBNgBBfKmuawyIlBfW3u2KKdW+H3OXPH9OgocaF1i2sWQkZgID+yQfZYjcdB8AJ5xKKTd6sIo+CPfKF5WadE7JeVt4Ytn5mzU/YOyuadCDY8V5To64XkL0uZgEQjyp3XsuiPVsuV54GICgu0qgVcNL3usWg7ir0ZsqsQdU1+hqkbsV7Neh5PbX7b+JmaHnV40l7xS2a583/MfSgZMdzQ8TXrFXvj9MaN8pcnC6i/qu5KgOD+9jGvUEiIVBKFT2JtBYubRqpY8p53iAE/sHscqcunN4z6gtfFVBNdCWfBlNVRK11qI4gJaVHnfsHZhT7uBxLjAS+927on2ZkqwXGC6IT8QONzYq9B8OFmKD/GLkY3JxaBycyX4TmLj0DwjSrQOceEAMOSfvywF+lXgF7kvABhk+kEXl/rLZyuRfzidK7yZr5/7k5dQbedgtHJj3GnxBbF0158UvvblPG6Tm2Gf75m38svWj7Qkl1C3IeOYZBl+9ZT3n8A/AHI0zZp7CltF8eMLQGQrjw+RF0t/pxys322MXIiFokZ6nLGMRX8cLAM1w0pDt7lUImTlqBskA2HpRrOzA1WXdmQlzTZIsx8IQlxt7B6l+Eq2gTFNRE8nwv3W/Nbntxmx7LMu8ZYTOKcQlyCOwiCBlp6EI9cs1hgF6chpVG3wz8BQr7f2q08u8pX+dsA==
  template:
    metadata:
      name: ghcr-secret
      namespace: hawakening
    type: kubernetes.io/dockerconfigjson
