apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawakening-backend
  namespace: hawakening
  labels:
    app: hawakening-backend
spec:
  replicas: 5 # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hawakening-backend
  template:
    metadata:
      labels:
        app: hawakening-backend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: hawakening-backend
      containers:
        - name: hawakening-backend
          image: ghcr.io/hawakening/hawakening-services-backend:v0.52.2
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          livenessProbe:
            httpGet:
              path: /liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: hawakening-backend
  namespace: hawakening
  labels:
    app: hawakening-backend
spec:
  selector:
    app: hawakening-backend
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 4000
      # nodePort: 30002 # Specify a node port if you want a specific port, otherwise it will be auto-assigned
  type: LoadBalancer
