apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawakening-backend
  namespace: hawakening
  labels:
    app: hawakening-backend
spec:
  replicas: 5 # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hawakening-backend
  template:
    metadata:
      labels:
        app: hawakening-backend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: hawakening-backend
      containers:
        - name: hawakening-backend
          image: ghcr.io/hawakening/hawakening-services-backend:v0.50.2
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URL
            - name: GOOGLE_RECAPTCHA_V2_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_RECAPTCHA_V2_SECRET_KEY
            - name: ORCHESTRATOR_GHCR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: ORCHESTRATOR_GHCR_USERNAME
            - name: ORCHESTRATOR_GHCR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: ORCHESTRATOR_GHCR_PASSWORD
            - name: SITE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SITE_URL
            - name: METEOR_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: METEOR_URI
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MAIL_PORT
            - name: MAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: MAIL_USER
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MAIL_PASS
            - name: LOG_LEVEL
              value: http
            # - name: DISABLE_REGISTRATION
            #   value: "true"
            - name: REDIS_SENTINEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_SENTINEL_HOST
            - name: REDIS_SENTINEL_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_SENTINEL_PORT
            - name: REDIS_MASTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_MASTER_NAME
            - name: CLI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: CLI_API_KEY
          livenessProbe:
            httpGet:
              path: /liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: hawakening-backend
  namespace: hawakening
  labels:
    app: hawakening-backend
spec:
  selector:
    app: hawakening-backend
  ports:
    - protocol: TCP
      port: 30002
      targetPort: 4000
      # nodePort: 30002 # Specify a node port if you want a specific port, otherwise it will be auto-assigned
  type: LoadBalancer
