apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawakening-frontend
  namespace: hawakening
  labels:
    app: hawakening-frontend
spec:
  replicas: 3 # Number of replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hawakening-frontend
  template:
    metadata:
      labels:
        app: hawakening-frontend
    spec:
      containers:
        - name: hawakening-frontend
          image: ghcr.io/hawakening/hawakening-services-frontend:v0.28.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: ghcr-secret
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: hawakening-frontend
