architecture: replicaset
replicaCount: 3
externalAccess:
  enabled: false
serviceAccount:
  create: true
automountServiceAccountToken: true
rbac:
  create: true
persistence:
  storageClass: "longhorn-single-local"
  size: 50Gi
resourcesPreset: large
podAntiAffinityPreset: hard

# TODO: Create SealedSecret
auth:
  ## @param auth.existingSecret Existing secret with MongoDB(&reg;) credentials (keys: `mongodb-passwords`, `mongodb-root-password`, `mongodb-metrics-password`, `mongodb-replica-set-key`)
  ## NOTE: When it's set the previous parameters are ignored.
  ##
  existingSecret: "mongodb"
  usernames: ["hawakening"]
  databases: ["hawakening"]

## https://github.com/syndikat7/mongodb-rust-ping
## https://github.com/bitnami/charts/issues/10264

customLivenessProbe:
  failureThreshold: 6
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10
  # exec:
  #   command:
  #     - /custom-scripts/mongodb-rust-ping
  #     - --ping
  # You can choose between --ping and --hello , ping executes a ping command,
  # while hello checks if it is primary and writeable or secondary

customReadinessProbe:
  initialDelaySeconds: 6
  timeoutSeconds: 10
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 6
  # exec:
  #   command:
  #     - /custom-scripts/mongodb-rust-ping
  #     - --hello
# initContainers:
#   - name: download-ping-tool
#     image: busybox:1.36.0
#     imagePullPolicy: Always
#     command:
#       - sh
#       - -c
#       - |
#         #!/usr/bin/env bash -e
#         wget -O /custom-scripts/mongodb-rust-ping.tar.gz  \
#         "https://github.com/syndikat7/mongodb-rust-ping/releases/download/v0.3.1/mongodb-rust-ping-linux-x64.tar.gz"
#         cd /custom-scripts/ && tar -xzvf mongodb-rust-ping.tar.gz
#         chmod +x /custom-scripts/mongodb-rust-ping
#     volumeMounts:
#       - mountPath: "/custom-scripts"
#         name: mongodb-ping-volume

# extraVolumeMounts:
#   - name: mongodb-ping-volume
#     mountPath: /custom-scripts

# extraVolumes:
#   - name: mongodb-ping-volume
#     emptyDir:
#       sizeLimit: 100Mi
